### ISSUE TITLE
not working on mac

### ISSUE THREAD

**Issue by ad34** [KoltesDigital/shadertoy-exporter#4]
Seems that this is not working on mac. I tried first to copy paste url from chrome : copy / paste it not working.

then I typed the full url and select a preset, clicked on "open shader" nothing happens. no error message.

**Comment by KoltesDigital** [comment]
Hi, sorry for the delay.

Can you please check if the new version fixes the problem? https://github.com/KoltesDigital/shadertoy-exporter/releases

**Comment by KoltesDigital** [comment]
No answer.

**Comment by ad34** [comment]
Sorry I missed the first reply, checkin now

**Comment by ad34** [comment]
It s better but I m stuck with the export button at the button , it cannot be clicked  https://www.dropbox.com/sh/kdieq16rq1fz3fa/AABGJuqxPzWVskMOfwOrOHNwa?dl=0

**Comment by KoltesDigital** [comment]
Please click on `Select directory and prefix`, I know it's not clear.

**Comment by ad34** [comment]
it works , thanks !
