### ISSUE TITLE
GIF export looks choppy

### ISSUE THREAD

**Issue by wrightwriter** [KoltesDigital/shadertoy-exporter#7]
This is with the latest ffmpeg.

**Comment by KoltesDigital** [comment]
Can you share an example please?

**Comment by wrightwriter** [comment]
Hm, seems to be working fine now!

**Comment by KoltesDigital** [comment]
Hm the code hasn't changed. Have you upgraded your ffmpeg by any chance?

**Comment by wrightwriter** [comment]
No, it just started working without me changing anything. Now everything is smooth!
